### PR TITLE
nls supported and other fix

### PR DESCRIPTION
**Pull request by heartacker**
also fix to error: place to top of menu to avoid being divided by other

### CODE REVIEW

**Comment by heartacker** [comment]
nls zh support
image

image

**Comment by heartacker** [comment]
fix the being divided
- old
image

- new 
image

**Comment by electrotype** [comment]
@heartacker  Thank you for this contribution!

I'll deploy a new version soon.

**Comment by electrotype** [comment]
Version 2.2.0 now published and available.

**Pull request merged**
